#Parameters for the
#results_dir: /Users/maryk.thompson/Desktop/Davislab/OneDriveNexus365/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/
results_dir: ../../brain_results/300522_run/
results_dir_inctest: ../../brain_results/220722_inctest_run/
results_dir_pherson: ../../brain_results/270722_pherson/
inspect_dir: ../../brain_results/300522_run/inspect/
#this database doesn't have the ERCCs, only the SIRVs
gffutils_db: ../../resources/dmel_628_elex.db
out_fmt: 'png'
out_dpi: 300
